import './globals.css';
import type { Metadata } from 'next';
import { Inter, Outfit, Archivo } from 'next/font/google';
import { ThemeProvider } from '@/shared/providers/theme-provider';
import { Header } from '@/widgets/header/header';
import ReactQueryProvider from '@/shared/providers/reactQueryProvider';
import React from 'react';
import { Toaster } from '@/shared/ui/sonner';
import localFont from 'next/font/local';
import { DebugPanel } from '@/widgets/testingPanel/debugPanel';

const inter = Archivo({ subsets: ['latin'], weight: '400' });
const kodeMono = localFont({
  src: '../../public/fonts/Salmapro.otf',
  display: 'swap',
  weight: '400',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} bg-hash dark:bg-darkSpace`}>
        <ReactQueryProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Header />
            {children}
            {/*<DebugPanel />*/}
            <Toaster richColors={true} />
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
